version: '3.8'

services:
  # Development environment
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production environment
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # PostgreSQL Database (Standalone)
  postgres:
    image: postgres:15-alpine
    container_name: newsale_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: newsale_db
      POSTGRES_USER: newsale_user
      POSTGRES_PASSWORD: newsale_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - newsale_network
    profiles:
      - db
      - dev

  # pgAdmin (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: newsale_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newsale.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - newsale_network
    profiles:
      - db
      - dev

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: newsale_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - newsale_network
    profiles:
      - db
      - dev

  # Supabase local development (optional)
  supabase:
    image: supabase/supabase:latest
    ports:
      - '54321:8000' # Supabase Studio
      - '54322:5432' # PostgreSQL
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    profiles:
      - supabase

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local
  supabase_data:

networks:
  newsale_network:
    driver: bridge
